# go to sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=y

# increase transmission power of antenna to see if this overcomes connectivity issues
# may change in increments of 4 from minus20 to plus8 which is the max, default is 0
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y